# wsl = false
# no-multigrid = false
# vsync = true
# maximized = false
# srgb = false
# idle = true
neovim-bin = "/opt/homebrew/bin/nvim"
frame = "buttonless"
# title-hidden = true
# tabs = true

[font]
normal = ["MesloLGS NF"]
size = 16
