# Original Lion PATH: /usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin
export PATH=$HOME/.rbenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin

export EDITOR=vim

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Load rbenv
eval "$(rbenv init -)"
